user:
  email:
    min_length: 10
    max_length: 255
    regex_format: !ruby/regexp /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  name:
    max_length: 50
  password:
    min_length: 6
  gravatar:
    size: 50
time:
    expired_password: 2
paging:
  posts_per_page: 7
image:
  width_size: 500
  height_size: 500
  accept_img: "image/jpeg,image/gif,image/png"
  limit_size: 5
